hydra:
  searchpath:
    - file://external/verl/verl/trainer/config
    - file://config

defaults:
  - ppo_trainer
  - beyond_agent_dataflow_for_launcher
  - _self_

# Env Service 变量
env_service:
  env_url: "http://localhost:8080"
  env_type: "appworld"

# Verl setting
actor_rollout_ref:
  actor:
    clip_ratio_high: 0.28
    optim:
      lr: 1e-6
    ppo_mini_batch_size: 8
    ppo_micro_batch_size_per_gpu: 1
    use_kl_loss: true
    kl_loss_coef: 0.001
    ppo_max_token_len_per_gpu: 25580
    off_cliprange_high: 0.6
    kl_loss_type: low_var_kl
    entropy_coeff: 0
    fsdp_config:
      param_offload: true
      optimizer_offload: true
  rollout:
    val_kwargs:
      n: 8
      temperature: 0.9
    use_qwen3: false
    enable_request_id: false
    prompt_length: 20480
    response_length: 4096
    temperature: 0.9
    sparse: true
    log_prob_micro_batch_size_per_gpu: 1
    max_model_len: 25580
    log_prob_max_token_len_per_gpu: 25580
    tensor_model_parallel_size: 1
    mode: async
    name: vllm
    gpu_memory_utilization: 0.6
    n: 8
  ref:
    log_prob_max_token_len_per_gpu: 25580
    log_prob_micro_batch_size_per_gpu: 1
    fsdp_config:
      param_offload: true
  model:
    path: "/mnt/data/zouanni.zan/models/Qwen2.5-14B-Instruct" # input
    use_remove_padding: true
    enable_gradient_checkpointing: true

algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false

data:
  train_batch_size: 32
  max_prompt_length: 4000
  max_response_length: 21580
  filter_overlong_prompts: true
  truncation: error
  return_raw_chat: true
  train_files: null
  val_files: null

trainer:
  n_gpus_per_node: 8
  critic_warmup: 0
  logger: ["console", "swanlab"]
  project_name: appworld
  nnodes: 1
  save_freq: 10
  test_freq: 10
  total_epochs: 40
  val_before_train: True
  default_local_dir: "experiments/${trainer.experiment_name}/checkpoints"  # checkpoint output
  validation_data_dir: "experiments/${trainer.experiment_name}/validation_log" # output
  rollout_data_dir: "experiments/${trainer.experiment_name}/rollout_log" # output

# self-questioning
task_manager:
  n: 0
  train_data_path: "/mnt/data/zouanni.zan/synthetic_data/tasks_explored.train.appworld0909_1.json"  # 输入
  mixture:
    synthetic_data_ratio: 999999
    original_data_ratio: 0
    use_original_tasks: false
  grader:
    synthetic_grader: llm-binary-gt-no_constraint

# self-navigating
experience_maker:
  base_url: "http://localhost:8001"
  enable_context_generator: false
  enable_summarizer: false
  workspace_id: "qwen2.5-14b_appworld_syndata"
  updated_freq: 0
hybrid_experience_training:
  val_rollout_expmode: "woexp"
  train_rollout_expmode: "mixed"
  train_sample_expmode: "discard"
  rollout_expratio: 0.25
  train_sample_keepratio: 0.0

# self-attributing
attribution_driven_credit_assignment:
  enable: false
  adca_grpo:
    enable_adca_metric: true
    prm_scheme: decouple
    alpha: 0.1
    skip_type: none
    equal_trajectory_weight: true
  evaluation_type: api
  consistent_scale: 1.0
  pos_unconsistent_scale: 0.2
  neg_unconsistent_scale: 0.2
  model: qwen-plus
  llm_evaluation_log_dir: "experiments/${trainer.experiment_name}/llm_evaluation_logs"  # output
